  GNU nano 3.2                                                                                    docker-compose.yml

version: '3.4'

services:

# telegram bot
  sensorberry-bot:
    container_name: sensorberry-bot
    build: .
    volumes:
      - .:/usr/src/app
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    depends_on:
      - mariadb
    links:
      - mariadb
    privileged: true

# phpmyadmin
#  phpmyadmin:
#    depends_on:
#      - mariadb
#    image: phpmyadmin/phpmyadmin
#    restart: unless-stopped
#    ports:
#      - '8080:80'
#    environment:
#      - PMA_HOST= mariadb
#      - MARIADB_ROOT_PASSWORD=DEY1syRA6JC39UDU
#    links:
#      - mariadb

# database
  mariadb:
    container_name: libri-db
    image: jsurf/rpi-mariadb
    volumes:
      - ./mariadb-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=DEY1syRA6JC39UDU
      - MYSQL_DATABASE=databerry
      - MYSQL_USER=databerry
      - MYSQL_PASSWORD=DEY1syRA6JC39UDU
